### PR TITLE
Change Emoji loading technique

### PR DESCRIPTION
**Pull request by octplane**
If emojis_json_lua.lua is missing, the file is generated at boot by
reading the json and saving it to this lua file: first boot is still slow, but next boots are nearly "instant".

Loading time is much faster!

### CODE REVIEW

**Comment by aldur** [comment]
Thanks for the contribution, it's a nice idea!

About the loading time, could you comment more on "nearly instant"?
I took some really rough measurements on a 2017 Macbook Pro, 13'', i5.
`master` loads in around 1m30s, while your branch makes it in 1m10s. Do you get better results?

**Comment by octplane** [comment]
My own conf . takes 3s to start the Emoji Spoon:
```
2018-03-07 13:48:45: Starting Emoji Spoon.
2018-03-07 13:48:47: Emoji Spoon: Started.
```

I will check that the branch I pushed is correct :D...

**Comment by octplane** [comment]
I have added some logging during startup. Here is what I get:

```
018-03-07 13:56:06: Starting Emojis Spoon...
2018-03-07 13:56:08: -- Loading extension: chooser
2018-03-07 13:56:09: Emojis Spoon: Startup completed
```

**Comment by octplane** [comment]
🙇  Thanks for your quick feedback!

**Pull request merged**
